### ISSUE TITLE
Merging collections not working

### ISSUE THREAD

**Issue by Globegitter** [rtablada/eloquent-ember#8]
Sorry to just open issue after issue, but just ran into the next one.

I have two different queries and want to merge them together as describe here:
https://coderwall.com/p/ebqwgw

But I am getting the following error. I can sort of make sense out of it and see the constructor needs two more parameters $sideloads, $modelKey, so still seeing what I can figure out. But can you think of a quick workaround/fix?

![capture decran 2014-02-13 a 12 14 34](https://f.cloud.github.com/assets/2580254/2162461/78052908-94d2-11e3-9d21-e0bf5f8b863f.png)

Edit: Yeah, I tried a couple of workarounds myself (like union), but not able to find a fix. Any help would really be appreciated.

**Comment by rtablada** [comment]
That should do it I hope. I don't have a test case for it so I'll need you to check.

**Comment by Globegitter** [comment]
That did indeed fix it. Thank you so much.
